
seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444
  environment:
    - GRID_TIMEOUT=60000
    - GRID_BROWSER_TIMEOUT=60000

chromenode:
  image: selenium/node-chrome-debug
  volumes:
      - /dev/shm:/dev/shm
  ports:
    - 5900
  links:
    - seleniumhub:hub

firefoxnode:
  image: selenium/node-firefox-debug
  volumes:
      - /dev/shm:/dev/shm
  ports:
    - 5901
  links:
    - seleniumhub:hub
